CREATE TABLE site_contents (
    id         CHAR(36)     NOT NULL PRIMARY KEY,
    `key`      VARCHAR(100) NOT NULL UNIQUE,
    value      JSON         NOT NULL,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
