-- Production seed: real catalog data from template-produk-pisau.xlsx
-- Generated by Claude Code — review before running against production.
-- Safe to re-run: categories/products are skipped if a matching slug already exists.
-- NOTE: product photos are NOT included. The source spreadsheet's "Gambar" sheet only
-- has Tokopedia *listing page* links (not direct image files), and this project's policy
-- is to never hotlink/scrape external site images. Upload real photos per product via
-- the admin panel after import — see seeds/tokopedia_reference_links.md for the list.

START TRANSACTION;

-- ============ Categories ============
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT '06b9fc80-4cbf-4410-a986-5a70a0c76a8f', 'Slicer', 'slicer', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'slicer');
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT '99f64a09-c88a-4e27-9408-4b23080a9ae5', 'K-Tip Gyuto', 'k-tip-gyuto', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'k-tip-gyuto');
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT '40355b4b-f8d9-405e-bf00-f64f85719f53', 'Gyuto', 'gyuto', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'gyuto');
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT 'a6241e3f-8b50-495e-9a7d-5a16138cdb0c', 'Deba', 'deba', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'deba');
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT 'd77fd6f2-574a-4637-830c-bc01c317f4da', 'Petty', 'petty', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'petty');
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT '0823bb8d-6ced-40b8-8d95-3a603174770d', 'Honesuki', 'honesuki', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'honesuki');
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT '5fcb3311-3ae6-4eb3-a104-d0472c93fda6', 'Yanagiba', 'yanagiba', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'yanagiba');
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT 'e412501c-8037-4a7e-9760-242e5561a26a', 'Taiwan', 'taiwan', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'taiwan');
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT '00797767-cff1-4ee8-a7be-b3a049b49864', 'Kiritsuke', 'kiritsuke', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'kiritsuke');
INSERT INTO categories (id, name, slug, created_at, updated_at)
SELECT 'fd1a9ba2-171d-4f84-98e8-e40b1aa739b7', 'Bunka', 'bunka', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'bunka');

-- ============ Products ============
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'b2a17ccc-e65c-4caa-bc3a-27b218841697', (SELECT id FROM categories WHERE slug = 'slicer'), 'Slicer HSS Nashiji Finish 215mm', 'slicer-hss-nashiji-finish-215mm', 'Slicer knife adalah pisau dapur yang dirancang untuk memotong daging, roast, dan bahan bertekstur lembut dengan irisan tipis dan rapi. Menggunakan baja HSS (High Speed Steel) yang unggul dalam ketahanan aus dan daya tahan ketajaman, pisau ini mampu memberikan hasil potong yang halus dan konsisten, bahkan dalam penggunaan intensif. Bilahnya yang panjang dan ramping memudahkan satu tarikan potong tanpa merusak struktur daging, sementara pegangan ergonomis memastikan kenyamanan dan kontrol optimal bagi penggunanya.', NULL, 385000, 425000, 'IDR', NULL, 'sale', 1, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'db420d1a-f2a5-4823-a44c-b6e5762e93b2', (SELECT id FROM categories WHERE slug = 'k-tip-gyuto'), 'K-Tip Gyuto HSS Nashiji Finish 205mm', 'k-tip-gyuto-hss-nashiji-finish-205mm', 'K-tip gyuto adalah pisau dapur Jepang yang memadukan karakter serbaguna dari gyuto dengan ujung khas “kiritsuke tip” yang runcing dan presisi tinggi. Menggunakan baja HSS (High Speed Steel) yang unggul dalam ketahanan aus dan daya tahan ketajaman, pisau ini memberikan performa potong yang konsisten, tajam, dan responsif untuk berbagai teknik seperti slicing, chopping, hingga detail work yang membutuhkan akurasi tinggi. Desain ujung K-tip memungkinkan kontrol lebih baik saat memotong bahan kecil atau membuat potongan presisi, sementara bilah yang panjang dan sedikit melengkung tetap menjaga alur potong yang halus. Dipadukan dengan pegangan ergonomis, K-tip gyuto menjadi pilihan ideal bagi chef', NULL, 910000, 950000, 'IDR', NULL, 'sale', 1, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT '5a885824-c22c-4a9a-82df-901ae15c9627', (SELECT id FROM categories WHERE slug = 'slicer'), 'Slicer HSS Kurouchi Finish 210mm', 'slicer-hss-kurouchi-finish-210mm', 'Slicer knife adalah pisau dapur yang dirancang untuk memotong daging, roast, dan bahan bertekstur lembut dengan irisan tipis dan rapi. Menggunakan baja HSS (High Speed Steel) yang unggul dalam ketahanan aus dan daya tahan ketajaman, pisau ini mampu memberikan hasil potong yang halus dan konsisten, bahkan dalam penggunaan intensif. Bilahnya yang panjang dan ramping memudahkan satu tarikan potong tanpa merusak struktur daging, sementara pegangan ergonomis memastikan kenyamanan dan kontrol optimal bagi pengguna profesional maupun pecinta kuliner.', NULL, 860000, 900000, 'IDR', NULL, 'sale', 1, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT '46916a45-8557-4d21-b48b-ef8a5e1cbff7', (SELECT id FROM categories WHERE slug = 'gyuto'), 'Gyuto Nashiji Finish 210mm', 'gyuto-nashiji-finish-210mm', 'Gyuto adalah pisau chef serbaguna yang dirancang untuk berbagai teknik pemotongan, mulai dari mengiris hingga mencincang dengan presisi tinggi. Menggunakan bahan HSS (High Speed Steel) yang sangat keras dan tahan aus, pisau ini menawarkan ketajaman superior yang bertahan lama serta performa stabil meski digunakan intensif. Dengan desain bilah seimbang dan pegangan ergonomis, Gyuto HSS menjadi pilihan ideal bagi chef profesional maupun pecinta kuliner yang mengutamakan kekuatan, akurasi, dan daya tahan maksimal.', NULL, 910000, 950000, 'IDR', NULL, 'sale', 1, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'd44e059a-cca5-412b-a0f2-e4ce2ed130a9', (SELECT id FROM categories WHERE slug = 'deba'), 'Deba High Speed Steel 165mm', 'deba-high-speed-steel-165mm', NULL, NULL, 960000, 1000000, 'IDR', NULL, 'sale', 1, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'f3867f53-109c-4eb5-b8f9-95cc114aa630', (SELECT id FROM categories WHERE slug = 'gyuto'), 'Gyuto Amboyna Blue Resin Handle 240mm', 'gyuto-amboyna-blue-resin-handle-240mm', 'Gyuto adalah pisau chef serbaguna yang dirancang untuk berbagai teknik pemotongan, mulai dari mengiris hingga mencincang dengan presisi tinggi. Menggunakan bahan HSS (High Speed Steel) yang sangat keras dan tahan aus, pisau ini menawarkan ketajaman superior yang bertahan lama serta performa stabil meski digunakan intensif. Dengan desain bilah seimbang dan pegangan ergonomis, Gyuto HSS menjadi pilihan ideal bagi chef profesional maupun pecinta kuliner yang mengutamakan kekuatan, akurasi, dan daya tahan maksimal.', NULL, 2460000, 2500000, 'IDR', NULL, 'sale', 1, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT '505f9eb5-0bb9-4580-bb98-c351a792610c', (SELECT id FROM categories WHERE slug = 'gyuto'), 'Gyuto HSS with Dyed Alder Wood Handle 210mm', 'gyuto-hss-with-dyed-alder-wood-handle-210mm', 'Gyuto adalah pisau chef serbaguna yang dirancang untuk berbagai teknik pemotongan, mulai dari mengiris hingga mencincang dengan presisi tinggi. Menggunakan bahan HSS (High Speed Steel) yang sangat keras dan tahan aus, pisau ini menawarkan ketajaman superior yang bertahan lama serta performa stabil meski digunakan intensif. Dengan desain bilah seimbang dan pegangan ergonomis, Gyuto HSS menjadi pilihan ideal bagi chef profesional maupun pecinta kuliner yang mengutamakan kekuatan, akurasi, dan daya tahan maksimal.', NULL, 1835000, 1875000, 'IDR', NULL, 'sale', 1, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'facea88b-92c8-4e6c-ae06-21a72fddf768', (SELECT id FROM categories WHERE slug = 'k-tip-gyuto'), 'K-tip Gyuto Kurouchi Hight Speed Steel 215mm', 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm', 'K-tip gyuto adalah pisau dapur Jepang yang memadukan karakter serbaguna dari gyuto dengan ujung khas “kiritsuke tip” yang runcing dan presisi tinggi. Menggunakan baja HSS (High Speed Steel) yang unggul dalam ketahanan aus dan daya tahan ketajaman, pisau ini memberikan performa potong yang konsisten, tajam, dan responsif untuk berbagai teknik seperti slicing, chopping, hingga detail work yang membutuhkan akurasi tinggi. Desain ujung K-tip memungkinkan kontrol lebih baik saat memotong bahan kecil atau membuat potongan presisi, sementara bilah yang panjang dan sedikit melengkung tetap menjaga alur potong yang halus. Dipadukan dengan pegangan ergonomis, K-tip gyuto menjadi pilihan ideal bagi chef', NULL, 960000, 1000000, 'IDR', NULL, 'sale', 1, 300, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'ceb62eea-b5ff-4634-98e0-074988a54c01', (SELECT id FROM categories WHERE slug = 'gyuto'), 'Gyuto Kurouchi High Speed Steel 210mm', 'gyuto-kurouchi-high-speed-steel-210mm', 'Gyuto adalah pisau chef serbaguna yang dirancang untuk berbagai teknik pemotongan, mulai dari mengiris hingga mencincang dengan presisi tinggi. Menggunakan bahan HSS (High Speed Steel) yang sangat keras dan tahan aus, pisau ini menawarkan ketajaman superior yang bertahan lama serta performa stabil meski digunakan intensif. Dengan desain bilah seimbang dan pegangan ergonomis, Gyuto HSS menjadi pilihan ideal bagi chef profesional maupun pecinta kuliner yang mengutamakan kekuatan, akurasi, dan daya tahan maksimal.', NULL, 910000, 950000, 'IDR', NULL, 'sale', 1, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-210mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'd5108962-996d-4e38-bbc4-09b3ed203d62', (SELECT id FROM categories WHERE slug = 'petty'), 'Petty Kurouchi High Speed Steel 140mm', 'petty-kurouchi-high-speed-steel-140mm', NULL, NULL, 735000, 775000, 'IDR', NULL, 'sale', 1, 100, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT '12d36058-070f-4ffd-8735-f4553e7d4c32', (SELECT id FROM categories WHERE slug = 'slicer'), 'Slicer L6 210mm', 'slicer-l6-210mm', 'Slicer adalah pisau khusus yang di rancanag untuk menghasilkan irisan tipis dan rapi, terutama pada daging, ikan dan bahan bertekstur lembut. Dengan bilah yang panjang dan ramping, slicer memungkinkan potong lurus, halus, dan konsisten tanpa merusak serat bahan.', NULL, 610000, 650000, 'IDR', NULL, 'sale', 1, 100, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-l6-210mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT '66f1262a-0db6-41b7-af21-4fe533b12f54', (SELECT id FROM categories WHERE slug = 'k-tip-gyuto'), 'K-tip Gyuto N695 Stainless Steel 210mm', 'k-tip-gyuto-n695-stainless-steel-210mm', 'K-tip gyuto adalah pisau dapur Jepang yang memadukan karakter serbaguna dari gyuto dengan ujung khas “kiritsuke tip” yang runcing dan presisi tinggi. Menggunakan baja N695 stainless steel yang dikenal tahan karat, mudah dirawat, dan memiliki ketajaman yang stabil, pisau ini memberikan performa potong yang konsisten, presisi, dan andal untuk berbagai teknik seperti slicing, chopping, hingga detail work yang membutuhkan akurasi tinggi. Desain ujung K-tip memungkinkan kontrol lebih baik saat menangani bahan kecil atau membuat potongan halus, sementara bilah yang panjang dan sedikit melengkung menjaga alur potong tetap mulus. Dipadukan dengan pegangan ergonomis, K-tip gyuto N695 menjadi pilihan ideal bagi penggunanya.', NULL, 1810000, 1850000, 'IDR', NULL, 'sale', 1, 300, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT '1badf2aa-2d0c-4246-8321-b27289d888e8', (SELECT id FROM categories WHERE slug = 'gyuto'), 'Gyuto Kurouchi High Speed Steel 235mm', 'gyuto-kurouchi-high-speed-steel-235mm', 'Gyuto Kurouchi – 235mmPisau Gyuto adalah interpretasi Jepang dari chef’s knife yang dirancang untuk serba guna di dapur profesional maupun rumahan. Dengan bilah sepanjang 235mm, pisau ini mampu menangani berbagai teknik pemotongan, mulai dari memotong daging besar hingga mengiris sayuran halus dengan presisi tinggi.
Finishing Kurouchi menghadirkan tampilan hitam alami yang merupakan hasil dari proses tempa tradisional. Lapisan ini bukan hanya memberikan karakter rustic dan elegan, tetapi juga berfungsi sebagai perlindungan tambahan terhadap oksidasi ringan.
Fungsi Utama
Memotong dan mengiris daging merah, ikan, dan unggas dengan mudah.
Mengolah berbagai jenis sayuran keras maupun lembut.
Mencincang bumbu dan rempah dengan kontrol penuh.
Membuat potongan tipis slicing untuk hidangan presisi.
Keunggulan Pisau Gyuto Kurouchi
Bilah Tajam & Presisi – Terbuat dari baja berkualitas, memberikan ketajaman luar biasa yang tahan lama.
Finishing Kurouchi Tradisional – Memberikan perlindungan sekaligus estetika klasik Jepang.
Desain Ergonomis – Seimbang dan nyaman digenggam, mengurangi rasa lelah saat pemakaian intensif.
Serbaguna – Cocok digunakan baik oleh koki profesional maupun pecinta masak rumahan yang mengutamakan kualitas.
Pisau ini bukan sekadar alat dapur, melainkan perpaduan seni tradisi Jepang dan fungsionalitas modern, menjadikannya pilihan tepat bagi siapa pun yang mengutamakan presisi, ketajaman, dan keindahan dalam setiap potongan.', NULL, 910000, 950000, 'IDR', NULL, 'sale', 1, 300, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'f22ecfae-5a5f-415f-9b57-8a5406fe7f6b', (SELECT id FROM categories WHERE slug = 'honesuki'), 'Honesuki Carbon Steel  155mm', 'honesuki-carbon-steel-155mm', NULL, NULL, 410000, 450000, 'IDR', NULL, 'sale', 2, 100, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT '1bbe8a77-bf4c-4408-9fc9-0227ab529634', (SELECT id FROM categories WHERE slug = 'yanagiba'), 'Yanagiba Akeno Carbon Steel 240mm', 'yanagiba-akeno-carbon-steel-240mm', 'Yanagiba knife adalah pisau dapur Jepang yang sangat penting untuk pemotongan presisi tinggi, terutama dalam persiapan sashimi dan sushi. Dengan bilah panjang, ramping, dan sangat tajam, serta material berkualitas tinggi, yanagiba menawarkan kehalusan dan presisi yang dibutuhkan untuk teknik pemotongan yang cermat. Pegangan ergonomis dan perawatan yang tepat memastikan pisau ini tetap menjadi alat andalan dalam dapur, baik untuk koki profesional maupun penggemar masakan Jepang di rumah.', NULL, 485000, 525000, 'IDR', NULL, 'sale', 4, 150, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT '0e7859f1-9570-4ff0-97da-c441b21fff65', (SELECT id FROM categories WHERE slug = 'slicer'), 'Slicer Knife Akeno Carbon Steel 175mm', 'slicer-knife-akeno-carbon-steel-175mm', 'Pisau ini dirancang khusus untuk memotong ikan, terutama tuna, dengan presisi tinggi. Dikenal karena bilahnya yang panjang dan ramping, pisau ini memungkinkan pemotongan yang halus, ideal untuk persiapan sushi dan sashimi.', NULL, 710000, 750000, 'IDR', NULL, NULL, 1, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT '85499d69-690c-4a39-a871-4bf73c965113', (SELECT id FROM categories WHERE slug = 'taiwan'), 'Taiwan Tuna Akeno 170mm', 'taiwan-tuna-akeno-170mm', 'Pisau tuna Taiwan adalah alat dapur yang dirancang khusus untuk memotong ikan, terutama tuna, dengan presisi tinggi. Dikenal karena bilahnya yang panjang dan ramping, pisau ini memungkinkan pemotongan yang halus, ideal untuk persiapan sushi dan sashimi.', NULL, 660000, 700000, 'IDR', NULL, 'sale', 1, 200, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'taiwan-tuna-akeno-170mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'e20a2b4f-5835-47c9-acb3-f877a05c70df', (SELECT id FROM categories WHERE slug = 'kiritsuke'), 'Kiritsuke Kimimaro N695 220mm', 'kiritsuke-kimimaro-n695-220mm', 'Pisau Kiritsuke merupakan simbol dari kecanggihan dan keahlian dalam memasak Jepang. Dengan desain yang elegan dan fungsionalitas yang luar biasa, pisau ini adalah pilihan ideal bagi koki profesional dan penggemar masakan. Memiliki pisau Kiritsuke dari pisaupedia adalah langkah cerdas untuk meningkatkan pengalaman memasak Anda.', NULL, 2510000, 2550000, 'IDR', NULL, 'sale', 1, 250, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm');
INSERT INTO products (id, category_id, name, slug, description, care_instructions, price, compare_at_price, currency, maker, badge, stock, weight, is_active, created_at, updated_at)
SELECT 'fc62056d-fb88-49ac-bd2d-fde321f554b9', (SELECT id FROM categories WHERE slug = 'bunka'), 'Bunka Akeno Carbon Steel 165mm', 'bunka-akeno-carbon-steel-165mm', 'Bunka knife adalah pisau dapur Jepang yang menggabungkan desain serbaguna dengan fungsionalitas tinggi. Dengan bilah yang lebar dan sedikit melengkung, serta material berkualitas tinggi, bunka knife menawarkan ketajaman dan kontrol yang sangat baik untuk berbagai tugas dapur. Pegangan ergonomis dan perawatan yang tepat memastikan pisau ini tetap menjadi alat andalan di dapur, baik untuk koki profesional maupun penggemar masakan di rumah. Dengan keahlian dan desain yang elegan, bunka knife adalah pilihan yang sangat baik untuk mereka yang menghargai keindahan dan efisiensi dalam setiap potongan.', NULL, 435000, NULL, 'IDR', NULL, 'sale', 10, 500, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm');

-- ============ Product specs ============
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'daeaff72-1bd4-4649-a130-ecf2ee5d831b', (SELECT id FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm'), 'Blade Shape', 'Slicer', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-nashiji-finish-215mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '5fdf2ee6-f050-4335-bdc9-0c6c7066f161', (SELECT id FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm'), 'Steel Type', 'High Speed Steel (HSS)', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-nashiji-finish-215mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'f8632e84-19e7-4368-83e1-e05ec0ad759a', (SELECT id FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm'), 'Blade Length', '215mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-nashiji-finish-215mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '4b29321a-ef18-46e2-9d33-3d1e66955523', (SELECT id FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm'), 'Blade Height', '35mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-nashiji-finish-215mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '4f693adc-beac-4679-b0b9-721bf752be6f', (SELECT id FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm'), 'Spine Thickness', '2.2mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-nashiji-finish-215mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '0b6c7dbe-671c-47a6-a726-60e94cab4058', (SELECT id FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm'), 'Handle Length', '135mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-nashiji-finish-215mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '73c21bd3-aeac-4ad8-9b3d-dc89581323ae', (SELECT id FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-nashiji-finish-215mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'c3ce3925-fb52-4382-adae-bc20f60c5c44', (SELECT id FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm'), 'Handle Materials', 'Teak wood Ferule Ebony wood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-nashiji-finish-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-nashiji-finish-215mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'c5069ae7-4c17-4044-bdea-3b5dd39157d7', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm'), 'Blade Shape', 'K-tip Gyuto', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-hss-nashiji-finish-205mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '379c38d5-5dd5-4b1c-9f8e-344d2b40c440', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm'), 'Steel Type', 'High Speed Steel (HSS)', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-hss-nashiji-finish-205mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '5ee30d20-6b7e-49e0-a64d-b5c35cdae024', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm'), 'Blade Length', '205mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-hss-nashiji-finish-205mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'd5ed3d38-6a17-4cf4-86f0-bf2f0eec461f', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm'), 'Blade Height', '50mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-hss-nashiji-finish-205mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '2989cdcf-ea38-4b64-a0cb-7f36d9dca144', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm'), 'Spine Thickness', '2.3mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-hss-nashiji-finish-205mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '9cf952b9-b0bf-47ee-9efc-b81ce722c043', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm'), 'Handle Length', '140mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-hss-nashiji-finish-205mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '9e900c12-5730-4de2-bf8c-76190d153262', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-hss-nashiji-finish-205mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '603665cf-6a85-426a-8224-28f9b990b026', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm'), 'Handle Materials', 'Teak wood Ferule Ebony wood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-hss-nashiji-finish-205mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-hss-nashiji-finish-205mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '9856da44-3c75-4642-8b57-318e1e9eadd9', (SELECT id FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm'), 'Blade Shape', 'Slicer', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-kurouchi-finish-210mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '42226e36-94ac-4094-a58e-93db549b1d30', (SELECT id FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm'), 'Steel Type', 'High Speed Steel (HSS)', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-kurouchi-finish-210mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'e37b56a2-a404-4550-af26-006cb870cdc9', (SELECT id FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm'), 'Blade Length', '210mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-kurouchi-finish-210mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '1fa82411-40a8-4e11-9aca-22470dc61067', (SELECT id FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm'), 'Blade Height', '35mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-kurouchi-finish-210mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '1a988ff4-fa0a-4649-bee5-ced5f181acd0', (SELECT id FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm'), 'Spine Thickness', '2mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-kurouchi-finish-210mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '61307986-e008-45a5-b74b-2ade5aa6ebc7', (SELECT id FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm'), 'Handle Length', '135mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-kurouchi-finish-210mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '0a2ac374-b3f7-4a72-ad83-dee6ad1aecee', (SELECT id FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-kurouchi-finish-210mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '723dd5cc-aa83-4c99-a480-c0db12b9b8f9', (SELECT id FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm'), 'Handle Materials', 'Teak wood Ferule Ebony wood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-hss-kurouchi-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-hss-kurouchi-finish-210mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'a0521fd0-955a-425e-acdb-adf7843fa357', (SELECT id FROM products WHERE slug = 'gyuto-nashiji-finish-210mm'), 'Blade Shape', 'Gyuto Kurouchi', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-nashiji-finish-210mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '9221fa86-87ad-4ddb-a9ff-6a7486b1192c', (SELECT id FROM products WHERE slug = 'gyuto-nashiji-finish-210mm'), 'Steel Type', 'High Speed Steel (HSS)', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-nashiji-finish-210mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'b531bfd4-cdb1-495e-978a-462ad00febd4', (SELECT id FROM products WHERE slug = 'gyuto-nashiji-finish-210mm'), 'Blade Construction', 'Mono Steel', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-nashiji-finish-210mm' AND ps.label = 'Blade Construction');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'dddecd66-1480-42d1-ad2f-a8814ace5d37', (SELECT id FROM products WHERE slug = 'gyuto-nashiji-finish-210mm'), 'Blade Length', '210mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-nashiji-finish-210mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'b8e40a46-e2d5-4bfd-a2ba-c1b9453aced3', (SELECT id FROM products WHERE slug = 'gyuto-nashiji-finish-210mm'), 'Blade Height', '50mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-nashiji-finish-210mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '26225755-878c-4aa6-ac92-d51d51c2c4f5', (SELECT id FROM products WHERE slug = 'gyuto-nashiji-finish-210mm'), 'Spine Thickness', '2.4mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-nashiji-finish-210mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '6435a79b-b7da-4e2f-917a-2c0027444de9', (SELECT id FROM products WHERE slug = 'gyuto-nashiji-finish-210mm'), 'Handle Length', '140mm', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-nashiji-finish-210mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '16b95933-cb98-46b1-8157-84becca3cdec', (SELECT id FROM products WHERE slug = 'gyuto-nashiji-finish-210mm'), 'Handle Type', 'Wa Handle', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-nashiji-finish-210mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'a8f08164-fdb9-47df-bb82-45069bdd5b7a', (SELECT id FROM products WHERE slug = 'gyuto-nashiji-finish-210mm'), 'Handle Materials', 'Teak wood Ferule Ebony wood', 8
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-nashiji-finish-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-nashiji-finish-210mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'a7a7296f-da59-46a9-a7e1-e29fcfa80f92', (SELECT id FROM products WHERE slug = 'deba-high-speed-steel-165mm'), 'Blade Shape', 'Deba', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'deba-high-speed-steel-165mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '52c42d37-2116-410f-8206-ef0e068b5acc', (SELECT id FROM products WHERE slug = 'deba-high-speed-steel-165mm'), 'Steel Type', 'High Speed Steel (HSS)', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'deba-high-speed-steel-165mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '13f35147-204a-4431-855e-e31df0a9a5c0', (SELECT id FROM products WHERE slug = 'deba-high-speed-steel-165mm'), 'Blade Construction', 'Mono Steel (single bevel)', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'deba-high-speed-steel-165mm' AND ps.label = 'Blade Construction');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '91d292a4-3168-41b0-a1d8-d5ff5132ada0', (SELECT id FROM products WHERE slug = 'deba-high-speed-steel-165mm'), 'Blade Length', '165mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'deba-high-speed-steel-165mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '81786924-3c3c-4810-8022-34f26e1b5db1', (SELECT id FROM products WHERE slug = 'deba-high-speed-steel-165mm'), 'Blade Height', '48mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'deba-high-speed-steel-165mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '539f82bd-5622-4322-b487-e00b54fc8578', (SELECT id FROM products WHERE slug = 'deba-high-speed-steel-165mm'), 'Spine Thickness', '6mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'deba-high-speed-steel-165mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '1a7d3c3b-9fa9-4b73-a1d6-9c17aac3a516', (SELECT id FROM products WHERE slug = 'deba-high-speed-steel-165mm'), 'Handle Length', '130mm', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'deba-high-speed-steel-165mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '2f81ee12-05f1-4d6c-b3a1-066dec52a5ed', (SELECT id FROM products WHERE slug = 'deba-high-speed-steel-165mm'), 'Handle Type', 'Wa Handle', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'deba-high-speed-steel-165mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'be315c39-36b1-4e6d-8ea4-091b318aa4ab', (SELECT id FROM products WHERE slug = 'deba-high-speed-steel-165mm'), 'Handle Materials', 'Ebony wood', 8
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'deba-high-speed-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'deba-high-speed-steel-165mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '5242183d-9e68-4903-a98d-f37bb86775f4', (SELECT id FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm'), 'Blade Shape', 'Gyuto', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-amboyna-blue-resin-handle-240mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '4de50e04-1a77-4de5-9e8a-b99fef9caf7b', (SELECT id FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm'), 'Steel Type', 'D2 Steel', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-amboyna-blue-resin-handle-240mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '2464f17a-6917-4624-8e26-b9d59fd8cf8c', (SELECT id FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm'), 'Blade Length', '240mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-amboyna-blue-resin-handle-240mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '5232e6c0-8b09-4df7-9708-47b417258926', (SELECT id FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm'), 'Blade Height', '50mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-amboyna-blue-resin-handle-240mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'ab5bb49c-7918-4d1c-a57a-e8337cbbd615', (SELECT id FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm'), 'Spine Thickness', '2.5mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-amboyna-blue-resin-handle-240mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '1040fb0a-f470-44f8-a48e-ac7fc1fedf9d', (SELECT id FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm'), 'Handle Length', '140mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-amboyna-blue-resin-handle-240mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'd0088423-27fb-4ba9-803f-85a6d3012061', (SELECT id FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-amboyna-blue-resin-handle-240mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'e4ae5a1a-e02a-4ae7-8ca7-4490244b4e7c', (SELECT id FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm'), 'Handle Materials', 'Amboyna mix blue resin handle with ferrule blonde horn', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-amboyna-blue-resin-handle-240mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'cad5a091-8fc3-40a6-89a3-e32a4295f797', (SELECT id FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm'), 'Saya/sheath Material', 'Olive wood', 8
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-amboyna-blue-resin-handle-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-amboyna-blue-resin-handle-240mm' AND ps.label = 'Saya/sheath Material');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '0c105e96-b5ec-4fa0-82a9-cd368d5d338d', (SELECT id FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm'), 'Blade Shape', 'Gyuto', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'cc77e010-071d-40ea-b141-10ef9ab98f70', (SELECT id FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm'), 'Steel Type', 'High Speed Steel (HSS)', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'c83e75ee-bca0-4ee1-8adf-c0aa6fde6d0f', (SELECT id FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm'), 'Blade Length', '210mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'cea220fc-4dc7-437d-b732-8e9fb4162d9a', (SELECT id FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm'), 'Blade Height', '47mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'b98cace4-58f0-4014-8055-3b145a7d714a', (SELECT id FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm'), 'Spine Thickness', '2.2mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '2ea8b085-fdc3-4cae-8960-bd709d794fc2', (SELECT id FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm'), 'Handle Length', '135mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '60452427-47eb-4841-bfed-835539b91121', (SELECT id FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '37c09d7c-f5de-4975-8e6c-e67c81194c03', (SELECT id FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm'), 'Handle Materials', 'Dyed alder wood handle and blonde horn ferrule', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '785cb4dc-d5b6-4229-99c1-b7d086e6ce89', (SELECT id FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm'), 'Saya/sheath Material', 'Sycamore wood', 8
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-hss-with-dyed-alder-wood-handle-210mm' AND ps.label = 'Saya/sheath Material');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '9456ce0b-ff77-454d-8211-6b2d4ea3d59a', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm'), 'Blade Shape', 'K-tip Gyuto', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'b864113e-bf7d-43df-90bf-04c6bb4cffa8', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm'), 'Steel Type', 'High Speed Steel (HSS)', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'e2ab0650-162a-4eb2-8ed6-16a193be5e94', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm'), 'Blade Length', '215mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'd8305419-ea93-4630-a99d-0e7bce22141c', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm'), 'Blade Height', '45mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'cf145f63-c5b7-43bd-b9f5-3584774ff581', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm'), 'Spine Thickness', '2.7mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'a776aad9-8d33-455a-a84e-52059cdd1164', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm'), 'Handle Length', '140mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '95fa66f1-4dfc-4aaf-85c3-41e930b303bc', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '43a6f3ff-a400-40b7-af58-8a880fda14e9', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm'), 'Handle Materials', 'Curly wood with Ebony wood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-kurouchi-hight-speed-steel-215mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'a7f8b046-c59b-42b7-98a3-37e74e3706f5', (SELECT id FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm'), 'Blade Shape', 'Petty Kurouchi', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'petty-kurouchi-high-speed-steel-140mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'ff4de3d4-3305-482b-9561-a9bb1bd58b08', (SELECT id FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm'), 'Steel Type', 'High Speed Steel (HSS)', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'petty-kurouchi-high-speed-steel-140mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '95822d6b-83b1-4a75-adbf-4ee443ef4c16', (SELECT id FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm'), 'Blade Length', '140mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'petty-kurouchi-high-speed-steel-140mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'b5553695-cdf1-4247-8667-d209adebdf5e', (SELECT id FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm'), 'Blade Height', '30mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'petty-kurouchi-high-speed-steel-140mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'c0f821cb-a389-488c-a9ff-3f2c5f4b8d74', (SELECT id FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm'), 'Spine Thickness', '2.1mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'petty-kurouchi-high-speed-steel-140mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'f8a69586-088a-4ea8-bee7-d932996f22a6', (SELECT id FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm'), 'Handle Length', '120mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'petty-kurouchi-high-speed-steel-140mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '008d49a2-f1e6-4898-ace1-3651ac720013', (SELECT id FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'petty-kurouchi-high-speed-steel-140mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'petty-kurouchi-high-speed-steel-140mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'a8947843-0ad2-411d-a3a8-450eba6ccc25', (SELECT id FROM products WHERE slug = 'slicer-l6-210mm'), 'Blade Shape', 'Slicer', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-l6-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-l6-210mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '2dd7d2e1-ed8b-4cc1-81c8-df3a0df37f12', (SELECT id FROM products WHERE slug = 'slicer-l6-210mm'), 'Steel Type', 'L6', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-l6-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-l6-210mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'bee93ce6-5e93-4379-8c93-f5c8c0f3acdc', (SELECT id FROM products WHERE slug = 'slicer-l6-210mm'), 'Blade Length', '210mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-l6-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-l6-210mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'e5f34a74-2776-42e6-afc3-6b16c7b8acca', (SELECT id FROM products WHERE slug = 'slicer-l6-210mm'), 'Blade Height', '30mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-l6-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-l6-210mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'aba470ac-8bd0-4b0c-9d71-cf2e363311c3', (SELECT id FROM products WHERE slug = 'slicer-l6-210mm'), 'Spine Thickness', '1.2mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-l6-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-l6-210mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '63fa52db-16ad-40eb-8b07-e2cdb213e6a8', (SELECT id FROM products WHERE slug = 'slicer-l6-210mm'), 'Handle Length', '135mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-l6-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-l6-210mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '3906a8c2-ca15-40d1-a0fd-209f7c7a1856', (SELECT id FROM products WHERE slug = 'slicer-l6-210mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-l6-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-l6-210mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '176795c0-8da9-4ed6-adb2-16c831661aa6', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm'), 'Blade Shape', 'K-tip Gyuto', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-n695-stainless-steel-210mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'caf659a4-b06d-4fe4-a19c-01c1fa0242ca', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm'), 'Steel Type', 'N695 Stainless Steel', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-n695-stainless-steel-210mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '89254fe7-da37-4100-ba5d-e04e1e6198ef', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm'), 'Blade Length', '210mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-n695-stainless-steel-210mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '4213b30b-a182-4240-bae0-f26fc768b669', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm'), 'Blade Height', '50mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-n695-stainless-steel-210mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'a0b06896-d7f7-4b0e-86ab-f2eccf4ee4bd', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm'), 'Spine Thickness', '2.5mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-n695-stainless-steel-210mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '9969c8c0-7a19-4b2e-b4c4-c9cef1af0cb6', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm'), 'Handle Length', '145mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-n695-stainless-steel-210mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'f763a819-22cb-4c88-8ffc-57da8f67d5cf', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-n695-stainless-steel-210mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'eb440967-8835-414d-922d-f2323d8f59a6', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm'), 'Handle Materials', 'Amboyna wood with verule Ebony wood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-n695-stainless-steel-210mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '0b11f539-88fa-4881-bf2f-b5db588a1884', (SELECT id FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm'), 'Saya/sheath Material', 'Peach', 8
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'k-tip-gyuto-n695-stainless-steel-210mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'k-tip-gyuto-n695-stainless-steel-210mm' AND ps.label = 'Saya/sheath Material');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '59fd6ef8-5319-4623-9857-7c45d36bbda5', (SELECT id FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm'), 'Blade Shape', 'Gyuto Kurouchi', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-kurouchi-high-speed-steel-235mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '37b65d95-0d0c-4aac-aa6c-178e9e0fae23', (SELECT id FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm'), 'Steel Type', 'High Speed Steel (HSS)', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-kurouchi-high-speed-steel-235mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '038843b3-0b15-41fa-b0c2-73bdc9752e2e', (SELECT id FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm'), 'Blade Construction', 'Mono Steel', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-kurouchi-high-speed-steel-235mm' AND ps.label = 'Blade Construction');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '262d7665-d0ba-4590-b271-c1f9001cf623', (SELECT id FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm'), 'Blade Length', '235mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-kurouchi-high-speed-steel-235mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'd43d62d0-2f4a-4a47-a014-278ad6edd022', (SELECT id FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm'), 'Blade Height', '45mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-kurouchi-high-speed-steel-235mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '65cec949-28bb-4832-9769-c7308049f0b6', (SELECT id FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm'), 'Spine Thickness', '2mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-kurouchi-high-speed-steel-235mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '20a2eed2-f025-426f-86e7-d7d22fb6b8b6', (SELECT id FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm'), 'Handle Length', '140mm', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-kurouchi-high-speed-steel-235mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'a1e50320-c12c-4a95-a35a-71f835182993', (SELECT id FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm'), 'Handle Type', 'Wa Handle', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'gyuto-kurouchi-high-speed-steel-235mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'gyuto-kurouchi-high-speed-steel-235mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '8bec6c50-e2dd-42ff-8981-071e85e23fb7', (SELECT id FROM products WHERE slug = 'honesuki-carbon-steel-155mm'), 'Blade Shape', 'Honesuki', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'honesuki-carbon-steel-155mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '4e17e263-f472-4450-b92c-f1394cadf6e4', (SELECT id FROM products WHERE slug = 'honesuki-carbon-steel-155mm'), 'Steel Type', 'Carbon steel', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'honesuki-carbon-steel-155mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '99817482-b13f-46b7-befe-a8a5489a2d9e', (SELECT id FROM products WHERE slug = 'honesuki-carbon-steel-155mm'), 'Blade Construction', 'Mono Steel', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'honesuki-carbon-steel-155mm' AND ps.label = 'Blade Construction');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '69c9adad-ea8d-49dd-bd5a-c8872992ef19', (SELECT id FROM products WHERE slug = 'honesuki-carbon-steel-155mm'), 'Blade Length', '155mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'honesuki-carbon-steel-155mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'd6377606-bc26-4143-9a29-7ed1b5123fc7', (SELECT id FROM products WHERE slug = 'honesuki-carbon-steel-155mm'), 'Blade Height', '40mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'honesuki-carbon-steel-155mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '1d321e2f-e2d0-4d97-8096-76cfc28fb9f3', (SELECT id FROM products WHERE slug = 'honesuki-carbon-steel-155mm'), 'Spine Thickness', '1.5mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'honesuki-carbon-steel-155mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '201f5e65-164e-42bf-8128-b2f19fd100e2', (SELECT id FROM products WHERE slug = 'honesuki-carbon-steel-155mm'), 'Handle Length', '130mm', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'honesuki-carbon-steel-155mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '52f2a7d9-28bd-4781-b123-a45bd18509b2', (SELECT id FROM products WHERE slug = 'honesuki-carbon-steel-155mm'), 'Handle Type', 'Wa Handle', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'honesuki-carbon-steel-155mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '968d92f0-93e7-4073-8108-2703cfc5f705', (SELECT id FROM products WHERE slug = 'honesuki-carbon-steel-155mm'), 'Handle Materials', 'Teakwood with Rosewood Ferule Coated', 8
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'honesuki-carbon-steel-155mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'honesuki-carbon-steel-155mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '46a3f959-66cd-4377-abe8-6bdb2c3a460d', (SELECT id FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm'), 'Blade Shape', 'Yanagiba', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'yanagiba-akeno-carbon-steel-240mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'd2e45ab8-2ecb-43b1-853a-1716fa0dafd3', (SELECT id FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm'), 'Steel Type', 'ex Carl Schlieper Wooden Saw', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'yanagiba-akeno-carbon-steel-240mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '51f60870-897f-4bf0-b891-bbf7d12e367c', (SELECT id FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm'), 'Blade Length', '240mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'yanagiba-akeno-carbon-steel-240mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '8015055a-c4ec-4a0c-8aa6-354cbdfeee85', (SELECT id FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm'), 'Blade Height', '35mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'yanagiba-akeno-carbon-steel-240mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'cbc2c109-8e3f-4be7-b119-e2cc2d68b796', (SELECT id FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm'), 'Spine Thickness', '3mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'yanagiba-akeno-carbon-steel-240mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'ecea2a27-2e0b-4584-8a35-9232377009d5', (SELECT id FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm'), 'Handle Length', '130mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'yanagiba-akeno-carbon-steel-240mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '3954eb37-d72c-4ecd-9338-33b044b8b8b1', (SELECT id FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'yanagiba-akeno-carbon-steel-240mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '10753795-348c-4287-90d3-e3008ee2baad', (SELECT id FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm'), 'Handle Materials', 'Teakwood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'yanagiba-akeno-carbon-steel-240mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'yanagiba-akeno-carbon-steel-240mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'f350f737-8c4d-4842-8430-c7c503f8eaa4', (SELECT id FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm'), 'Blade Shape', 'Slicer (Taiwan Tuna)', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-knife-akeno-carbon-steel-175mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '2c21cfe3-a14e-43b0-99f1-858e31116d19', (SELECT id FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm'), 'Steel Type', 'Carbon Steel ex Carl Schlieper Wooden Saw', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-knife-akeno-carbon-steel-175mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '1c6952ef-d7a9-43eb-a72c-804c7d23cf68', (SELECT id FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm'), 'Blade Length', '175mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-knife-akeno-carbon-steel-175mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '0b69b261-f0bb-48a9-8c36-b3effce7f365', (SELECT id FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm'), 'Blade Height', '85mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-knife-akeno-carbon-steel-175mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '3b8864c3-259f-48f4-bb58-c9ef6894f8a5', (SELECT id FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm'), 'Spine Thickness', '3mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-knife-akeno-carbon-steel-175mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '2327919c-035f-4347-a301-3b45d67b382e', (SELECT id FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm'), 'Handle Length', '130mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-knife-akeno-carbon-steel-175mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '29c33a35-7acc-49f5-b452-5d581cf15acc', (SELECT id FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-knife-akeno-carbon-steel-175mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'f01f083f-9ff1-4823-9464-569bbf60f1f6', (SELECT id FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm'), 'Handle Materials', 'Teakwood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'slicer-knife-akeno-carbon-steel-175mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'slicer-knife-akeno-carbon-steel-175mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'e2988783-c162-4249-9451-b4d85999d72e', (SELECT id FROM products WHERE slug = 'taiwan-tuna-akeno-170mm'), 'Blade Shape', 'Taiwan Tuna', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'taiwan-tuna-akeno-170mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'taiwan-tuna-akeno-170mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'b6419259-da43-471d-a257-924a4bdcc1ac', (SELECT id FROM products WHERE slug = 'taiwan-tuna-akeno-170mm'), 'Steel Type', 'Carbon Steel ex Carl Schlieper Wooden Saw', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'taiwan-tuna-akeno-170mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'taiwan-tuna-akeno-170mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '20ecd594-e4a8-40ee-a376-e06ee3d7c537', (SELECT id FROM products WHERE slug = 'taiwan-tuna-akeno-170mm'), 'Blade Length', '175mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'taiwan-tuna-akeno-170mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'taiwan-tuna-akeno-170mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'faee8a57-8dc3-4bd7-a688-67ee3b0e1043', (SELECT id FROM products WHERE slug = 'taiwan-tuna-akeno-170mm'), 'Blade Height', '90mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'taiwan-tuna-akeno-170mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'taiwan-tuna-akeno-170mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'c296da49-1688-4967-b227-a9d2f9c84122', (SELECT id FROM products WHERE slug = 'taiwan-tuna-akeno-170mm'), 'Spine Thickness', '2.5mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'taiwan-tuna-akeno-170mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'taiwan-tuna-akeno-170mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '82f2de4b-7fc6-4a17-a26a-83b818211348', (SELECT id FROM products WHERE slug = 'taiwan-tuna-akeno-170mm'), 'Handle Length', '130mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'taiwan-tuna-akeno-170mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'taiwan-tuna-akeno-170mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'd07d758a-b0d5-4a9b-b279-e4913c6b69a4', (SELECT id FROM products WHERE slug = 'taiwan-tuna-akeno-170mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'taiwan-tuna-akeno-170mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'taiwan-tuna-akeno-170mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '6d02959f-ff6b-4c23-81f4-439d34f33aa5', (SELECT id FROM products WHERE slug = 'taiwan-tuna-akeno-170mm'), 'Handle Materials', 'Teakwood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'taiwan-tuna-akeno-170mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'taiwan-tuna-akeno-170mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'ae814984-0e42-4909-bc32-a405ec2d973e', (SELECT id FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm'), 'Blade Shape', 'Kiritsuke', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'kiritsuke-kimimaro-n695-220mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '33b8a097-eb0c-4289-8149-ab38bf36bb80', (SELECT id FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm'), 'Steel Type', 'N695 Stainless Steel', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'kiritsuke-kimimaro-n695-220mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'f840f969-9e2f-42d1-9b66-89065b2f0f08', (SELECT id FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm'), 'Blade Length', '220mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'kiritsuke-kimimaro-n695-220mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '27347bbd-e965-484d-a015-18a8f8f11a86', (SELECT id FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm'), 'Blade Height', '50mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'kiritsuke-kimimaro-n695-220mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'c6a112f7-48e2-454b-8d8d-bdd4f598feca', (SELECT id FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm'), 'Spine Thickness', '3mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'kiritsuke-kimimaro-n695-220mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'f068e7e6-0d39-4136-af82-6212148f3b7d', (SELECT id FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm'), 'Handle Length', '140mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'kiritsuke-kimimaro-n695-220mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'cfc8fe33-b829-4986-a9bc-333f7fb15f92', (SELECT id FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'kiritsuke-kimimaro-n695-220mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '22c63306-5470-47a2-b7d2-97ded864b85c', (SELECT id FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm'), 'Handle Materials', 'Acacia wood, Guava wood and Rosewood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'kiritsuke-kimimaro-n695-220mm' AND ps.label = 'Handle Materials');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '2a138790-2709-40b5-8d12-7683dcad607d', (SELECT id FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm'), 'Saya/sheath Material', 'Acacia wood', 8
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'kiritsuke-kimimaro-n695-220mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'kiritsuke-kimimaro-n695-220mm' AND ps.label = 'Saya/sheath Material');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'ac289f54-ddda-4d67-9570-d8e12ad87bc1', (SELECT id FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm'), 'Blade Shape', 'Bunka', 0
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'bunka-akeno-carbon-steel-165mm' AND ps.label = 'Blade Shape');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'a7b9df67-0080-4f06-9cbb-8d494a3c15b6', (SELECT id FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm'), 'Steel Type', 'Carbon steel ex stone circle saw', 1
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'bunka-akeno-carbon-steel-165mm' AND ps.label = 'Steel Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT 'df147332-2f2d-40e8-950e-32ef0b617d9c', (SELECT id FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm'), 'Blade Length', '165mm', 2
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'bunka-akeno-carbon-steel-165mm' AND ps.label = 'Blade Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '095de2f2-5634-49de-992c-3b834ba217d6', (SELECT id FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm'), 'Blade Height', '50mm', 3
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'bunka-akeno-carbon-steel-165mm' AND ps.label = 'Blade Height');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '9a3bc839-01df-4bdc-8347-b881192f63e3', (SELECT id FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm'), 'Spine Thickness', '2.4mm', 4
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'bunka-akeno-carbon-steel-165mm' AND ps.label = 'Spine Thickness');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '1fa45a36-7967-4e6e-841e-83f7bcb0950f', (SELECT id FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm'), 'Handle Length', '130mm', 5
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'bunka-akeno-carbon-steel-165mm' AND ps.label = 'Handle Length');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '02068239-f6d3-4c3b-8925-099676ce3d09', (SELECT id FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm'), 'Handle Type', 'Wa Handle', 6
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'bunka-akeno-carbon-steel-165mm' AND ps.label = 'Handle Type');
INSERT INTO product_specs (id, product_id, label, value, sort_order)
SELECT '8af327f4-4145-4066-9361-9fc37d50cf5f', (SELECT id FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm'), 'Handle Materials', 'Teakwood with Rosewood', 7
WHERE EXISTS (SELECT 1 FROM products WHERE slug = 'bunka-akeno-carbon-steel-165mm')
  AND NOT EXISTS (SELECT 1 FROM product_specs ps JOIN products p ON p.id = ps.product_id WHERE p.slug = 'bunka-akeno-carbon-steel-165mm' AND ps.label = 'Handle Materials');

COMMIT;
